on: [push]
name: build
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 10.x, 12.x, 14.x ]

    name: Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm build

      - name: Check formatting
        run: |
          npm run validate
          npx prettier --check "src/**/*.{svelte,ts,js}"
